version: '3.8'
services:
  app:
    image: openjdk:21
    container_name: parsing-service
    working_dir: /app
    volumes:
      - ./build/libs/parsing-service-0.0.1-SNAPSHOT.jar:/app/parsing-service.jar
    command: [ "java", "-jar", "parsing-service.jar" ]
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: itemdb
